spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000

alibaba:
  cloud:
    access-key: LTAI5t9y9ebXUA4DiEFX2zY6
    secret-key: zwjc8uayaIAi8ypjnMcl5sMDEYFkPN
    oss:
      endpoint: oss-cn-zhangjiakou.aliyuncs.com
      bucket: gmd-oss
